version: '3'

services:
  nodejs:
    build: .
    command: bash -c "npm run start"
    volumes:
      - .:/src
      - /src/node_modules
    ports:
      - "3000:3000"
    environment:
      TZ: 'Asia/Tokyo'
